### ISSUE TITLE
Use ?coords= instead of ?ll= as the endpoint for geographic queries.

### ISSUE THREAD

**Issue by arenius** [sfbrigade/ballotapi#4]
I think that it isn't immediately obvious what ?ll represents both because it is extremely abbreviated and because the double ell could be mistaken for other characters.  On my system ll and II are so similar that they're pretty much indistinguishable.  ?coords= is clearer.

Any thoughts?

**Comment by diafygi** [comment]
Needs to be updated in code.

**Comment by arenius** [comment]
Changed in code. Closing.
