### ISSUE TITLE
Large query results.

### ISSUE THREAD

**Issue by arenius** [sfbrigade/ballotapi#6]
I don't think this issue is a bug, just something we need to stay aware of.

/precincts/?elections=<id>[,<id>...]

Could return large amounts of data.  100MB + for all precincts in US, maybe?
Hard to estimate, depends on the data. (Eg, simple square-ish polygons vs. ones
with complicated shapes, etc)

/precincts/?election_dates=<start_date>:<end_date> is the above x10.  This query, depending on how it is called, could return every precinct in the database.

This isn't as much of a problem for /measures/?elections= because we aren't returning polygons.

**Comment by diafygi** [comment]
Agreed, probably need to paginate the datasets. All listed results should be formated somthing like this?

```javascript
{
    "count": 123,
    "offset": 0,
    "data": [
        <list of endpoint objects here>
    ]
}
```

**Comment by diafygi** [comment]
Added to spec. Need to implement in code.

**Comment by arenius** [comment]
I think this is now implemented to spec.  I would love if someone else tried it.  For now however I'm closing this as fixed.
